FROM <DOCKER_FROM>

RUN emerge-gitclone
RUN cd /var/lib/portage/coreos-overlay && git checkout build-<COREOS_MAJOR_VERSION>
RUN emerge -v coreos-sources coreos-modules autoconf libtool

# use package if available: -gK
# RUN emerge -gKv coreos-sources coreos-modules autoconf libtool
